# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e1560dd19f12fc97d4e11dda90a2514b"
name = "VizHog"
application_url = "https://vizhog-production.up.railway.app"
embedded = true
handle = "vizhog"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "orders/cancelled" ]
  uri = "pubsub://hello-conversions:vizhog-shopify-webhooks"

  [[webhooks.subscriptions]]
  topics = [ "refunds/create" ]
  uri = "pubsub://hello-conversions:vizhog-shopify-webhooks"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_themes,write_pixels,read_orders"

[auth]
redirect_urls = [
  "https://vizhog-production.up.railway.app/auth/callback",
  "https://vizhog-production.up.railway.app/auth/shopify/callback",
  "https://vizhog-production.up.railway.app/api/auth/callback"
]

[pos]
embedded = false
